services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\Filter\ChainFilterFormHandler:
        arguments:
            $formsHandler: !tagged_iterator { tag: 'erdnaxelaweb.ibexa_design_integration.pager.filter_form_handler', index_by: 'type' }

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\Filter\Form\CheckboxFormHandler:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.pager.filter_form_handler', type: 'checkbox' }

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\Filter\Form\RadioFormHandler:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.pager.filter_form_handler', type: 'radio' }

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\Filter\Form\DropdownFormHandler:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.pager.filter_form_handler', type: 'dropdown' }
