services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\PagerBuilder:
    ErdnaxelaWeb\IbexaDesignIntegration\Pager\PagerSearchFormBuilder:
    ErdnaxelaWeb\IbexaDesignIntegration\Pager\PagerActiveFiltersListBuilder:

    ErdnaxelaWeb\IbexaDesignIntegration\Event\Subscriber\PagerBuildSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    ErdnaxelaWeb\IbexaDesignIntegration\Configuration\PagerConfigurationManager:
        decorates: ErdnaxelaWeb\StaticFakeDesign\Configuration\PagerConfigurationManager
        parent: ErdnaxelaWeb\StaticFakeDesign\Configuration\PagerConfigurationManager
