services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ErdnaxelaWeb\IbexaDesignIntegrationBundle\Controller\DefaultViewController:
    public: true

  ErdnaxelaWeb\IbexaDesignIntegration\Helper\BreadcrumbGenerator:
  ErdnaxelaWeb\IbexaDesignIntegration\Helper\LinkGenerator:
  ErdnaxelaWeb\IbexaDesignIntegration\Helper\ImageGenerator:

  ErdnaxelaWeb\IbexaDesignIntegration\Fake\Generator\RichTextGenerator:
    decorates: ErdnaxelaWeb\StaticFakeDesign\Fake\Generator\RichTextGenerator
    lazy: true
    arguments:
      $richTextOutputConverter: '@ibexa.richtext.converter.output.xhtml5'

  ErdnaxelaWeb\IbexaDesignIntegration\Configuration\ContentConfigurationManager:
    decorates: ErdnaxelaWeb\StaticFakeDesign\Configuration\ContentConfigurationManager
    parent: ErdnaxelaWeb\StaticFakeDesign\Configuration\ContentConfigurationManager

  ErdnaxelaWeb\IbexaDesignIntegrationBundle\Command\GenerateParametersCommand:

  ErdnaxelaWeb\IbexaDesignIntegration\Migration\MigrationGenerator:
  ErdnaxelaWeb\IbexaDesignIntegrationBundle\Command\GenerateMigrationCommand:

  ErdnaxelaWeb\IbexaDesignIntegration\Fake\ChainGenerator:
    decorates: ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator
    parent: ErdnaxelaWeb\StaticFakeDesign\Fake\ChainGenerator
